# Generated by Django 5.1.3 on 2024-12-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_input', models.CharField(max_length=250)),
                ('number_result', models.IntegerField()),
            ],
        ),
    ]
